spring:
  profiles:
    active: localdev
  application:
    name: vmware
vmware:
  vnc:
    ip: 172.16.128.122
    port: 6080
    page: vnc.html
    portMin: 5900
    portMax: 6150
  network:
    enabled: false
    mapping: ("172.16.159.49","10.113.137.103";"172.16.128.60","10.113.137.104";"172.16.143.103","10.113.137.114")

desKey:
  key1: "1"
  key2: "2"
  key3: "3"

kmcScriptLocation: /opt/plugin/tomcat_https


